spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: eureka-user
      password: 12345

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false