spring:
  application:
    name: ms-cloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/Appcredit

server:
  port: 9091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-user:12345@${EUREKA_SERVER}:8761/eureka

      #defaultZone: http://localhost:8761/eureka
